### ISSUE TITLE
Please update readme 

### ISSUE THREAD

**Issue by GeekyShiva** [TheCraftKid/npm-hello-world#1]
Update information more about tests and functionalities of your repo.
What are the important components?

**Comment by WillieCubed** [comment]
Are you talking about how to use it in another program?

**Comment by GeekyShiva** [comment]
I am talking about , suppose someone wants to know about how this module works? and he is a complete beginner how would he understand this repository.
Just describe which file does what and how the file is built.

**Comment by WillieCubed** [comment]
Okay, I added some info on how to use the module.

**Comment by WillieCubed** [comment]
Actually, I'm having some merge issues with Git. It's [here](https://github.com/TheCraftKid/npm-hello-world/commit/2d1d1e24e8fe421c87505bf4aac131cd4489e6a3), though.

**Comment by WillieCubed** [comment]
And now they're fixed. @GeekyShiva

**Comment by GeekyShiva** [comment]
Looks great now
